### PR TITLE
fix result dialog showing null

### LINKED ISSUE #244: [PE-D][Tester D] Optional fields appear as null when not filled in the message shown.
Users are able to see null, which may be confusing to them.

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: lukkesreysandeur/ped#7

### LINKED ISSUE #245: [PE-D][Tester D] Exit command: App does not clear external pop ups from remind and help upon exit.
The pop ups that are generated are not immediately cleared after the exit command, so the app does not fully close.

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: lukkesreysandeur/ped#8

### LINKED ISSUE #257: [PE-D][Tester A] Lack of explanation of GUI
There is no explanation in the user guide for what the different parts of the ui mean and what their function is. Since certain buttons on the screen use only icons with no text, this is important to tell users as they could otherwise do something accidentally while trying to figure out what buttons do. 

-------------
Labels: `type.DocumentationBug` `severity.Medium`
original: Diamondroxxx/ped#6

### PR DESCRIPTION
**Pull request by zm-l**
fix #244 #245 #257

### CODE REVIEW

File: src/test/java/seedu/address/logic/commands/CommandTestUtil.java [hunk 1]
```diff
@@ -76,18 +63,6 @@ public class CommandTestUtil {
...
-    public static final String PHONE_DESC_AMY = " " + PREFIX_PHONE + VALID_PHONE_AMY;
-    public static final String PHONE_DESC_BOB = " " + PREFIX_PHONE + VALID_PHONE_BOB;
-    public static final String PHONE_DESC_PLACEHOLDER = " " + PREFIX_PHONE + VALID_PHONE_AMY;
-    public static final String EMAIL_DESC_AMY = " " + PREFIX_EMAIL + VALID_EMAIL_BANK_OF_AMERICA;
-    public static final String EMAIL_DESC_BOB = " " + PREFIX_EMAIL + VALID_EMAIL_BOB;
-    public static final String EMAIL_DESC_PLACEHOLDER = " " + PREFIX_EMAIL + VALID_EMAIL_BANK_OF_AMERICA;
-    public static final String ADDRESS_DESC_AMY = " " + PREFIX_ADDRESS + VALID_ADDRESS_AMY;
-    public static final String ADDRESS_DESC_BOB = " " + PREFIX_ADDRESS + VALID_ADDRESS_BOB;
-    public static final String TAG_DESC_FRIEND = " " + PREFIX_TAG + VALID_TAG_FRIEND;
-    public static final String TAG_DESC_HUSBAND = " " + PREFIX_TAG + VALID_TAG_HUSBAND;
```
Comment (jiasheng59) [inline src/test/java/seedu/address/logic/commands/CommandTestUtil.java:90]: Great!
